language: python
dist: focal
python:
  - "3.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:

  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp psutil
  - python3 -m pip install pytz
  - python3 -m pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot telegram motor

before_script:

  - if [ -f soul.c ]; then gcc soul.c -o soul -lpthread; fi

script:

  - chmod +x * && lscpu && python3 daku.py
  
                               